# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 1.0
default_acceleration_scaling_factor: 1.0

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  # hand joints
  # override URDF limits to avoid simulated position out of bounds due to floating-point epsilons 
  panda_finger_joint1:
    has_position_limits: true
    min_position: -0.0001
    max_position: 0.0401
    has_velocity_limits: true
    # fit with URDF
    max_velocity: 0.2
    has_acceleration_limits: true
    max_acceleration: 0.5
  panda_finger_joint2:
    has_position_limits: true
    min_position: -0.0001
    max_position: 0.0401
    has_velocity_limits: true
    max_velocity: 0.2
    has_acceleration_limits: true
    max_acceleration: 0.5
  
  # arm joints
  panda_joint1:
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: true
    max_acceleration: 0.5
  panda_joint2:
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: true
    max_acceleration: 0.5
  panda_joint3:
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: true
    max_acceleration: 0.5
  panda_joint4:
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: true
    max_acceleration: 0.5
  panda_joint5:
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: true
    max_acceleration: 0.5
  panda_joint6:
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: true
    max_acceleration: 0.5
  panda_joint7:
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: true
    max_acceleration: 0.5