controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster

# Controls the 7-DOF arm
panda_arm_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    # Allow MoveIt trajectories whose final velocities are not exactly zero
    allow_nonzero_velocity_at_trajectory_end: true


# Controls the 2-finger gripper
panda_hand_controller:
  ros__parameters:
    type: "joint_trajectory_controller/JointTrajectoryController"
    joints:
      - panda_finger_joint1 # only ACTUATED joint here
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    # PID controller settings
    gains:
      panda_finger_joint1:
        # Proportional gain: main stiffness term.
        # Larger P â†’ faster response, but more overshoot/oscillation.
        p: 15.0
        # Integral gain: corrects small steady-state error (e.g. friction).
        # Keep it small for the gripper to avoid slow oscillations.
        i: 3.0
        # Derivative gain: damping term.
        # Helps reduce overshoot and ringing when P and I are active.
        d: 0.8