# Fixed frame
header:
  frame_id: "world"

id: "composite_obstacle"
primitives:
  - type: "BOX"
    dimensions: [0.2, 0.2, 0.4]
  - type: "BOX"
    dimensions: [0.2, 0.2, 0.4]
  - type: "BOX"
    dimensions: [0.2, 0.05, 1.0]

primitive_poses:
  # Pose for BOX 1
  - position: {x: 0.45, y: 0.3, z: 0.2}
    orientation: {x: 0.0, y: 0.0, z: 0.0, w: 1.0}
  # Pose for BOX 2
  - position: {x: 0.45, y: -0.5, z: 0.2}
    orientation: {x: 0.0, y: 0.0, z: 0.0, w: 1.0}
  # Pose for BOX 3 - WALL
  - position: {x: 0.45, y: -0.1, z: 0.5}
    orientation: {x: 0.0, y: 0.0, z: 0.0, w: 1.0}
